### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by be4zad** [mrgick/duck_chat#7]
The API may return `[LIMIT_CONVERSATION]` at the end:
```
data: [DONE][LIMIT_CONVERSATION]
```

or may return:
```
{
    "action": "error",
    "r": "",
    "status": 429,
    "type": "ERR_SERVICE_UNAVAILABLE"
}
```

which causes:
```
DecodeError: JSON is malformed: invalid character (byte 1)
```

**Comment by mrgick** [comment]
Hello, @be4zad 

I need more data.
How many messages were in the chat, that triggered Limit conversations?

And yes, 429 is written when there are many requests to chat in duckduckgo

I think we can add handling of these errors (will raise error like TooManyRequest or LimitConservation)

What do you think about it?

**Comment by be4zad** [comment]
> How many messages were in the chat, that triggered Limit conversations?

I don't know. I guess more than 30 messages.

> And yes, 429 is written when there are many requests to chat in duckduckgo

Meaning of 429 is that many new conversation requested. Limit conversation is for many messages in the conversation requested.

> I think we can add handling of these errors (will raise error like TooManyRequest or LimitConservation)
> 
> What do you think about it?

That would be good.

**Comment by mrgick** [comment]
Okay, 

I'll add catching of these errors sometime on this week or next week, or you can try to add them

Have a good day =)

**Comment by mrgick** [comment]
Hello, @be4zad 

I released new version with handling errors =)
Exceptions are described in [exceptions.py](https://github.com/mrgick/duck_chat/blob/main/duck_chat/exceptions.py)

**Comment by be4zad** [comment]
Hi. Thank you.
I haven't tested it currently but I'll close the issue.
