### ISSUE TITLE
Auto grab all models from duck.ai

### ISSUE THREAD

**Issue by Troptrap** [mrgick/duck_chat#9]
```duck_chat
Using meta-llama/Llama-3-70b-chat-hf
Type /help to display the help
>>> User input №1:
hello
>>> Response №1:
Error occurred: ERR_MODEL_UNAVAILABLE
```

They use now
`meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo`

This is what I've seen in developer console. I'm not good enough to do it, but I wonder if one could reverse engineer the chat page to grab all available models dynamically instead of hardcoding (I'm lazy, I don't want to raise issues every other week lol).

**Comment by mrgick** [comment]
Hello @Troptrap 
Thanks for your PR -> I merged it and released v1.2.2 =)

About " if one could reverse engineer the chat page to grab all available models dynamically instead of hardcoding" I think I will try sometime (maybe I will create a small script to grab and use ci/cd to auto release new version with updated names) But, I can't promise, since it is a js page, maybe I'll have to use selenium/Puppeteer

**Comment by mrgick** [comment]
After trying, if it works, I'll write back and close the issue.

**Comment by Troptrap** [comment]
Alright, thanks. I was looking through all that obfuscated JS and I couldn't see any API call like duckduckgo.com/models (that would've been too easy hehe).  There is a div with a hard to remember class name that contains the <ul> tag with models. That class is also in the JS, I'm on mobile right now, can't copy/paste it here. 
It starts with "hoHa.......". I was thinking that maybe someone with more experience could deobfuscate the JS and see how it populates the models list.

**Comment by Troptrap** [comment]
I'm on the right track. Found this[ js file](https://duckduckgo.com/dist/wpm.3436.28af237b516db4733240.js) that contains the models list and it's available by curl. The models list is wrapped in a constant and it looks like this:

`const g=[{model:"gpt-4o",modelName:"GPT-4o",modelVariant:null,modelStyleId:"gpt-4o-mini",createdBy:"OpenAI",moderationLevel:"HIGH",isAvailable:!1,inputCharLimit:16e3,settingId:"4"},{model:"gpt-4o-mini",modelName:"GPT-4o",modelVariant:"mini",modelStyleId:"gpt-4o-mini",createdBy:"OpenAI",moderationLevel:"HIGH",isAvailable:!0,inputCharLimit:16e3,settingId:"3"},{model:"claude-3-5-sonnet-20240620",modelName:"Claude 3.5",modelVariant:"Sonnet",modelStyleId:"claude-3-haiku",createdBy:"Anthropic",moderationLevel:"HIGH",isAvailable:!1,inputCharLimit:16e3,settingId:"7"},{model:"claude-3-opus-20240229",modelName:"Claude 3",modelVariant:"Opus",modelStyleId:"claude-3-haiku",createdBy:"Anthropic",moderationLevel:"HIGH",isAvailable:!1,inputCharLimit:16e3,settingId:"2"},{model:"claude-3-haiku-20240307",modelName:"Claude 3",modelVariant:"Haiku",modelStyleId:"claude-3-haiku",createdBy:"Anthropic",moderationLevel:"HIGH",isAvailable:!0,inputCharLimit:16e3,settingId:"1"},{model:"meta-llama/Meta-Llama-3.1-70B-Instruct-Turbo",modelName:"Llama 3.1",modelVariant:"70B",modelStyleId:"llama-3",createdBy:"Meta",moderationLevel:"MEDIUM",isAvailable:!0,isOpenSource:!0,inputCharLimit:16e3,settingId:"5"},{model:"mistralai/Mixtral-8x7B-Instruct-v0.1",modelName:"Mixtral",modelVariant:"8x7B",modelStyleId:"mixtral",createdBy:"Mistral AI",moderationLevel:"LOW",isAvailable:!0,isOpenSource:!0,inputCharLimit:16e3,settingId:"6"}];`


Very easy to regex it from here and make it into a Python list. My only concern is that JS filenames may change over time. I have seen somewhere in all that obfuscated code that these wpm.3436.73737188477472.js files are constructed from simpler names. I'll dig more when I have time.

**Comment by mrgick** [comment]
Hello, you did a good research

I also found this file yesterday, but there is one problem, as you said " JS filenames may change over time".
As I see, duck.ai is using next (react like framework) with webpack (in js webpack is a tool that generates public static files
[framework-f8115f7fae64930e.js](https://duckduckgo.com/_next/static/chunks/framework-f8115f7fae64930e.js)

So, I'm trying to get every js file (get html file and get all js and then in all that files get all js again) and trying to find this structure =) 

![image](https://github.com/user-attachments/assets/dbc645a4-5999-47c8-8239-78f4be362398)

**Comment by mrgick** [comment]
Yep, also find "I have seen somewhere in all that obfuscated code that these wpm.3436.73737188477472.js files are constructed from simpler names. I'll dig more when I have time."

[js file](https://duckduckgo.com/dist/wpm.main.3a6708b9853f57763d7e.js)

![image](https://github.com/user-attachments/assets/ddf86eb8-079a-42e6-a5c5-2d504beb58c0)

**Comment by Troptrap** [comment]
It's difficult for me, I'm not quite an experienced programmer :) 
I'm able to find in the initial HTML (the one returned by https://duck.ai after redirects) the main JS script. That's the one with wpm.main. Then, inside that one, there is an object-like var that contains 3436.


I just noticed you posted a screenshot, that's where I am too. 3436 and the nonce are available. The only problem for me is where 3436 comes from.

**Comment by mrgick** [comment]
Okey, thanks)
I'll try to dig a bit more 

And I think maybe it will be easy just using tool like Puppeteer (emulating browser and use xpath/html scrapper) (maybe that's what I'll come to in the end)

**Comment by mrgick** [comment]
Hello again
I created [workflow](https://github.com/mrgick/duck_chat/blob/main/.github/workflows/generate_model.yml) - It will be auto create pull request, if models will change =)
Also, there is optional param --generate

**Comment by Troptrap** [comment]
I think I'm onto something with JS version, no Selenium. I'll update you with a gist here. Thanks for the efforts, from a maintainer perspective your solution is definitely easier and cleaner. But I want to see if it works the hard way also (decompiling webpack lol)

**Comment by mrgick** [comment]
Okey, good luck with "decompile webpack" ^^

**Comment by Troptrap** [comment]
https://gist.github.com/Troptrap/5990213baa44b30f39ae9707601a84cf

I'm curious if it will work in the future 😃
